
import React,{useEffect,useState} from "react";
import {Platform} from "react-native";
import {SafeAreaView,StatusBar,Text,View,TextInput,TouchableOpacity,ScrollView,ActivityIndicator,StyleSheet,Dimensions} from "react-native";
const API=(process.env.EXPO_PUBLIC_API_URL||"http://127.0.0.1:8000/api/v1").replace(/\/$/,"");
async function get(p){const r=await fetch(API+p);if(!r.ok)throw new Error(await r.text());return r.json()}
const money=(x)=>{const n=Number(x);if(!Number.isFinite(n))return"—";if(n>=1e12)return`$${(n/1e12).toFixed(2)}T`;if(n>=1e9)return`$${(n/1e9).toFixed(2)}B`;return`$${n.toFixed(2)}`};
const tabs=["Dashboard","Analysis","Company","Fundamentals","Research","Portfolio","Risk"];
export default function App(){
 const [ticker,setTicker]=useState("NVDA"),[input,setInput]=useState("NVDA"),[tab,setTab]=useState("Dashboard"),[stock,setStock]=useState(null),[company,setCompany]=useState(null),[fund,setFund]=useState(null),[portfolio,setPortfolio]=useState(null),[research,setResearch]=useState(null),[risk,setRisk]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=async(sym=ticker)=>{setBusy(true);setError("");try{const [s,c,f,p,r,ri]=await Promise.all([get(`/stock/${sym}`),get(`/company/${sym}`),get(`/fundamental/${sym}`),get(`/portfolio`),get(`/research/${sym}`),get(`/risk`)]);setStock(s);setCompany(c);setFund(f);setPortfolio(p);setResearch(r);setRisk(ri)}catch(e){setError(e.message)}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const runResearch=async()=>{setBusy(true);try{setResearch(await get(`/research/${ticker}?run=true`));setTab("Research")}catch(e){setError(e.message)}finally{setBusy(false)}};
 const q=stock?.quote||{},t=stock?.technical||{},p=company?.profile||company||{},dec=stock?.decision||{},doc=portfolio?.doctor||risk?.doctor||{};
 return <SafeAreaView style={s.safe}><StatusBar barStyle="light-content"/><View style={s.header}><View><Text style={s.eyebrow}>HQ · LIVE SYSTEM</Text><Text style={s.title}>HaViQuant</Text><Text style={s.sub}>360° Investment Intelligence</Text></View><Text style={s.live}>● LIVE</Text></View>
 <View style={s.search}><TextInput value={input} onChangeText={x=>setInput(x.toUpperCase())} style={s.input}/><TouchableOpacity style={s.go} onPress={()=>{const x=input.trim().toUpperCase();if(x){setTicker(x);load(x)}}}><Text style={s.goText}>Analyze</Text></TouchableOpacity></View>
 <ScrollView horizontal showsHorizontalScrollIndicator={false} style={s.tabs}>{tabs.map(x=><TouchableOpacity key={x} onPress={()=>setTab(x)} style={[s.tab,tab===x&&s.active]}><Text style={s.tabText}>{x}</Text></TouchableOpacity>)}</ScrollView>
 {busy&&!stock?<ActivityIndicator style={{margin:30}} color="#59ddff"/>:error?<View style={s.err}><Text style={s.errText}>{error}</Text></View>:<ScrollView style={s.body}>
 <Text style={s.h1}>{tab==="Dashboard"?`${ticker} Market Overview`:tab}</Text>
 {tab==="Dashboard"&&<><Hero ticker={ticker} name={p.name}/><Cards items={[["Price",money(q.price)],["Change",q.change_percent!=null?`${Number(q.change_percent).toFixed(2)}%`:"—"],["RSI",t.rsi!=null?Number(t.rsi).toFixed(2):"—"],["Decision",dec.action||dec.signal||"WATCH"]]}/><Text style={s.section}>Reactive market data</Text><Text style={s.muted}>The web client polls live quote data every second and refreshes history periodically.</Text></>}
 {tab==="Analysis"&&<><Hero ticker={ticker} name={p.name}/><Cards items={[["Price",money(q.price)],["Technical",t.score??t.technical_score??"—"],["Market Cap",money(p.market_cap)],["Decision",dec.action||dec.signal||"WATCH"]]}/><Technical t={t}/><Fundamental d={company}/></>}
 {tab==="Company"&&<><Hero ticker={ticker} name={p.name}/><Cards items={[["Sector",p.sector],["Industry",p.industry],["Market Cap",money(p.market_cap)],["Employees",p.employees?.toLocaleString()]]}/><Text style={s.section}>Business Overview</Text><Text style={s.muted}>{p.description||"No description returned."}</Text></>}
 {tab==="Fundamentals"&&<><Hero ticker={ticker} name={p.name}/><Fundamental d={fund}/></>}
 {tab==="Research"&&<><Hero ticker={ticker} name={p.name}/><TouchableOpacity style={s.run} onPress={runResearch}><Text style={s.runText}>Run Full Research</Text></TouchableOpacity><Text style={s.notice}>Research validation never changes the production BUY/SELL decision.</Text><Phase r={research?.phase_3_8} name="PHASE 3.8"/><Phase r={research?.phase_3_9} name="PHASE 3.9"/><Phase r={research?.phase_3_9_1} name="PHASE 3.9.1"/></>}
 {tab==="Portfolio"&&<><Cards items={[["Cash",money(portfolio?.portfolio?.cash)],["Health",doc.health??"—"],["Risk Score",doc.risk_score??"—"],["Positions",portfolio?.positions?.length??0]]}/><Text style={s.section}>Positions</Text>{(portfolio?.positions||[]).map((x,i)=><View style={s.row} key={i}><Text style={s.bold}>{x.ticker}</Text><Text style={s.muted}>{x.shares} shares · avg {money(x.average_cost)}</Text></View>)}</>}
 {tab==="Risk"&&<><Cards items={[["Health",doc.health??"—"],["Risk Score",doc.risk_score??"—"],["Valuation Coverage",doc.valuation_coverage!=null?`${Number(doc.valuation_coverage).toFixed(1)}%`:"—"],["P/L",money(doc.pnl??doc.total_pnl)]]}/><Text style={s.section}>Risk Findings</Text><Text style={s.muted}>{JSON.stringify(doc.findings||doc.risk_findings||[],null,2)}</Text></>}
 </ScrollView>}</SafeAreaView>
}
function Hero({ticker,name}){return <View style={s.hero}><Text style={s.badge}>360° INTELLIGENCE</Text><Text style={s.h2}>{ticker}</Text><Text style={s.muted}>{name||"—"}</Text></View>}
function Cards({items}){return <View style={s.cards}>{items.map(([a,b])=><View style={s.card} key={a}><Text style={s.label}>{a}</Text><Text style={s.value}>{b??"—"}</Text></View>)}</View>}
function Technical({t}){return <><Text style={s.section}>Technical Intelligence</Text><Cards items={[["Price",money(t.price)],["SMA20",money(t.sma20)],["SMA50",money(t.sma50)],["SMA200",money(t.sma200)],["RSI",t.rsi!=null?Number(t.rsi).toFixed(2):"—"],["MACD",t.macd!=null?Number(t.macd).toFixed(2):"—"]]}/></>}
function Fundamental({d}){const p=d?.profile||d||{},v=d?.valuation||{},pr=d?.profitability||{},g=d?.growth||{};return <><Text style={s.section}>Fundamental Intelligence</Text><Cards items={[["Market Cap",money(p.market_cap)],["P/E",v.pe??"—"],["Forward P/E",v.forward_pe??"—"],["Margin",pr.profit_margin!=null?`${(pr.profit_margin*100).toFixed(1)}%`:"—"],["ROE",pr.roe!=null?`${(pr.roe*100).toFixed(1)}%`:"—"],["Revenue Growth",g.revenue_growth!=null?`${(g.revenue_growth*100).toFixed(1)}%`:"—"]]}/></>}
function Phase({r,name}){return <View style={s.phase}><Text style={s.section}>{name} · {r?.status||"READY"}</Text><Text style={s.muted}>{r?JSON.stringify(r).slice(0,900):"Ready to execute the existing Python validation engine."}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#060b14"},header:{padding:16,flexDirection:"row",justifyContent:"space-between",borderBottomWidth:1,borderBottomColor:"#18283d"},eyebrow:{color:"#5d7894",fontSize:9,letterSpacing:2},title:{color:"#eaf4ff",fontSize:22,fontWeight:"900"},sub:{color:"#7189a4",fontSize:10},live:{color:"#63e3a0",fontSize:11},search:{margin:12,flexDirection:"row",backgroundColor:"#0b1625",borderRadius:10,borderWidth:1,borderColor:"#20334b"},input:{flex:1,color:"#fff",padding:11,fontWeight:"800"},go:{backgroundColor:"#123b50",padding:11,borderRadius:8},goText:{color:"#65ddff",fontWeight:"800"},tabs:{paddingHorizontal:10,maxHeight:50},tab:{padding:12},active:{borderBottomWidth:2,borderBottomColor:"#55dcff"},tabText:{color:"#8aa0b8",fontSize:12},body:{padding:14},h1:{color:"#eaf4ff",fontSize:25,fontWeight:"900",marginBottom:14},hero:{padding:18,backgroundColor:"#0b1726",borderRadius:14,borderWidth:1,borderColor:"#1a3048",marginBottom:14},badge:{color:"#60ddff",fontSize:9,fontWeight:"800"},h2:{color:"#fff",fontSize:32,fontWeight:"900",marginTop:8},muted:{color:"#8ba0b7",fontSize:12,lineHeight:19},cards:{flexDirection:"row",flexWrap:"wrap",gap:8,marginBottom:14},card:{backgroundColor:"#0b1725",borderWidth:1,borderColor:"#1a2d44",borderRadius:11,padding:12,width:"48%",minHeight:78},label:{color:"#69819c",fontSize:9,textTransform:"uppercase"},value:{color:"#edf6ff",fontSize:18,fontWeight:"800",marginTop:7},section:{color:"#e7f2ff",fontSize:15,fontWeight:"800",marginTop:12,marginBottom:9},run:{backgroundColor:"#123c50",padding:14,borderRadius:10,alignItems:"center"},runText:{color:"#69e0ff",fontWeight:"900"},notice:{marginTop:12,padding:12,color:"#8ca5be",backgroundColor:"#0b1928",borderRadius:9},phase:{padding:14,backgroundColor:"#0b1725",borderRadius:11,borderWidth:1,borderColor:"#1a2d44",marginTop:10},row:{padding:12,borderBottomWidth:1,borderBottomColor:"#17283b"},bold:{color:"#eaf4ff",fontWeight:"900"},err:{padding:20},errText:{color:"#ffafa6"}})
