import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Heart, Plus, ArrowLeft, Download, Users, CalendarDays } from 'lucide-react';
import './styles.css';

type Guest = {id:string;name:string;email:string;status:'Pending'|'Attending'|'Declined'|'Maybe'};
type Event = {id:string;title:string;host:string;date:string;time:string;location:string;message:string;design:string;guests:Guest[]};
const key='haviinvite.events.v1';
function load():Event[]{try {const data=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(data)?data:[];}catch{return [];}}
const blank=():Event=>({id:crypto.randomUUID(),title:'',host:'',date:'',time:'',location:'',message:'We would love to celebrate with you.',design:'rose',guests:[]});
const escape=(value:string)=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
function App(){
 const [events,setEvents]=useState(load);const [selected,setSelected]=useState('');const [draft,setDraft]=useState<Event|null>(null);const [tab,setTab]=useState('Invitation');const [notice,setNotice]=useState('');const [error,setError]=useState('');
 const event=events.find(e=>e.id===selected);
 function persist(next:Event[]){try{localStorage.setItem(key,JSON.stringify(next));setEvents(next);setError('');return true;}catch{setError('Could not save in this browser. Free up storage and try again.');return false;}}
 function save(e:React.FormEvent){e.preventDefault();if(!draft)return;if(!draft.title.trim()||!draft.host.trim()||!draft.location.trim()){setError('Enter an event name, host and location.');return;}if(persist(events.some(x=>x.id===draft.id)?events.map(x=>x.id===draft.id?draft:x):[...events,draft])){setSelected(draft.id);setDraft(null);setNotice('Event saved on this browser.');}}
 function download(){if(!event)return;const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${escape(event.title)}</title><body style="background:#fff4f1;color:#392438;font-family:Georgia,serif;padding:40px;text-align:center"><p>YOU’RE INVITED</p><h1>${escape(event.title)}</h1><p>Hosted by ${escape(event.host)}</p><p>${escape(event.date)} · ${escape(event.time)} (host’s local time)</p><p>${escape(event.location)}</p><p style="white-space:pre-wrap">${escape(event.message)}</p><p>Please contact your host to RSVP.</p></body></html>`;const url=URL.createObjectURL(new Blob([html],{type:'text/html'}));const a=document.createElement('a');a.href=url;a.download='invitation.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Invitation downloaded. Share the file with guests; responses are recorded by you.');}
 function addGuest(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!event)return;const form=e.currentTarget;const data=new FormData(form);const name=String(data.get('name')).trim();const email=String(data.get('email')).trim().toLowerCase();if(!name)return;if(event.guests.some(g=>g.email===email)){setError('That email is already on this guest list.');return;}if(persist(events.map(x=>x.id===event.id?{...x,guests:[...x.guests,{id:crypto.randomUUID(),name,email,status:'Pending'}]}:x))){form.reset();setNotice('Guest added. No message has been sent.');}}
 return <div className="invite-app"><header><a href="./world.html#product-invite" className="brand"><Heart/>HaVi<span>Invite</span></a><span className="local">Local workspace</span><a href="./world.html">HaVi World ↗</a></header><main>
 {error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="notice">{notice}</p>}
 {draft?<><button className="text-button" onClick={()=>{setDraft(null);setError('');}}><ArrowLeft size={16}/> Cancel</button><h1>{events.some(x=>x.id===draft.id)?'Edit your event':'Let’s make a moment.'}</h1><p className="muted">The details that bring everyone together.</p><form className="editor panel" onSubmit={save}>{(['title','host','date','time','location'] as const).map(field=><label key={field}>{({title:'Event name',host:'Hosted by',date:'Date',time:'Time (host’s local time)',location:'Location or meeting link'})[field]}<input required maxLength={field==='location'?500:160} type={field==='date'?'date':field==='time'?'time':'text'} value={draft[field]} onChange={e=>setDraft({...draft,[field]:e.target.value})}/></label>)}<label className="full">Your invitation message<textarea maxLength={2000} rows={4} value={draft.message} onChange={e=>setDraft({...draft,message:e.target.value})}/></label><fieldset className="full"><legend>Choose a design</legend><div className="designs">{['rose','midnight','sage'].map(design=><button type="button" key={design} className={`swatch ${design} ${draft.design===design?'chosen':''}`} aria-pressed={draft.design===design} onClick={()=>setDraft({...draft,design})}>{design}</button>)}</div></fieldset><button className="primary" type="submit">Save event</button></form></>
 :event?<><button className="text-button" onClick={()=>{setSelected('');setNotice('');}}><ArrowLeft size={16}/> All events</button><div className="heading"><div><p className="eyebrow">YOUR NEXT CELEBRATION</p><h1>{event.title}</h1><p className="muted">Hosted by {event.host}</p></div><button onClick={()=>setDraft({...event})}>Edit event</button></div><div className="tabs">{['Invitation','Guests & RSVPs','Delivery'].map(t=><button key={t} aria-pressed={tab===t} className={tab===t?'active':''} onClick={()=>{setTab(t);setError('');}}>{t}</button>)}</div>
 {tab==='Invitation'&&<div className="preview-grid"><article className={`invitation ${event.design}`}><Heart size={32}/><p className="eyebrow">YOU’RE INVITED</p><h2>{event.title}</h2><p>Hosted by {event.host}</p><div className="event-details"><p>{new Date(event.date+'T12:00:00').toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'})}</p><p>{event.time} · Host’s local time</p><p>{event.location}</p></div><p className="message">{event.message}</p><span className="signature">Made with HaViInvite</span></article><aside className="panel"><h2>Ready to bring people together?</h2><p>Download an invitation file to share with your guests. Ask them to reply directly to you, then record their response in the guest list.</p><button className="primary" onClick={download}><Download size={16}/> Download invitation</button><button onClick={()=>setTab('Guests & RSVPs')}><Users size={16}/> Manage guests</button><p className="muted">A public RSVP page is not connected yet. This workspace saves events only in this browser.</p></aside></div>}
 {tab==='Guests & RSVPs'&&<><div className="stats">{['Invited','Attending','Pending','Declined'].map(status=><div className="panel" key={status}><b>{status==='Invited'?event.guests.length:event.guests.filter(g=>g.status===status).length}</b><span>{status}</span></div>)}</div><section className="panel"><h2>Build your guest list</h2><form className="guest-form" onSubmit={addGuest}><label>Name<input name="name" required maxLength={120}/></label><label>Email<input name="email" type="email" required maxLength={254}/></label><button className="primary">Add guest</button></form><p className="muted">RSVP statuses are recorded manually by the host.</p>{!event.guests.length?<p className="empty">Your guest list is waiting for its first name.</p>:<div className="guest-list">{event.guests.map(g=><div className="guest" key={g.id}><div><b>{g.name}</b><small>{g.email}</small></div><label>RSVP<select aria-label={`RSVP for ${g.name}`} value={g.status} onChange={e=>{persist(events.map(x=>x.id===event.id?{...x,guests:x.guests.map(person=>person.id===g.id?{...person,status:e.target.value as Guest['status']}:person)}:x));}}>{['Pending','Attending','Maybe','Declined'].map(status=><option key={status}>{status}</option>)}</select></label></div>)}</div>}</section></>}
 {tab==='Delivery'&&<section className="panel"><h2>Share your invitation</h2><p>Download and share the invitation file using your preferred messaging app.</p><button className="primary" onClick={download}><Download size={16}/> Download invitation</button><div className="delivery"><h3>Email & SMS reminders</h3><p>Not connected. Automated sending and public RSVP links require a hosted service and a delivery provider.</p><button disabled>Delivery setup required</button></div></section>}</>
 :<><div className="heading"><div><p className="eyebrow">MOMENTS. PEOPLE. TOGETHER.</p><h1>Good moments start here.</h1><p className="muted">Beautiful invitations. Your favorite people. Something to look forward to.</p></div><button className="primary" onClick={()=>{setDraft(blank());setNotice('');}}><Plus size={18}/> Create event</button></div>{!events.length?<section className="empty-start panel"><Heart size={44}/><h2>Your first celebration awaits.</h2><p>Create an event, choose a design, and start your guest list.</p><button className="primary" onClick={()=>setDraft(blank())}>Create your first invitation</button></section>:<div className="event-grid">{events.map(e=><button className={`event-card ${e.design}`} key={e.id} onClick={()=>{setSelected(e.id);setTab('Invitation');setNotice('');}}><CalendarDays/><h2>{e.title}</h2><p>{e.date} · {e.time}</p><span>{e.guests.length} guests · {e.guests.filter(g=>g.status==='Attending').length} attending</span><strong>Open event →</strong></button>)}</div>}<p className="storage-note">Your events and guest lists are saved on this browser. No emails or texts are sent automatically.</p></>}
 </main><footer>HaViInvite · Celebrate beautifully.</footer></div>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
