import React,{useCallback,useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import {Activity,BarChart3,Building2,ChevronRight,FlaskConical,LayoutDashboard,Menu,Newspaper,PieChart,RefreshCw,Search,ShieldCheck,TrendingUp,Wallet,X,Zap} from "lucide-react";
import "./styles.css";
import AuthGate from "./auth/AuthGate";

const API=((import.meta as unknown as { env?: { VITE_API_URL?: string } }).env?.VITE_API_URL||"http://127.0.0.1:8000/api/v1").replace(/\/$/,"");
const periods=["1D","5D","1M","3M","6M","1Y","5Y"] as const;
const periodMap:Record<string,string>={"1D":"1d","5D":"5d","1M":"1mo","3M":"3mo","6M":"6mo","1Y":"1y","5Y":"5y"};
type Any=Record<string,any>;
type Page="Dashboard"|"Stock Analysis"|"Company Intelligence"|"Fundamentals"|"Technical"|"Decision"|"Evidence Research"|"Portfolio"|"Risk"|"Backtesting"|"News";
const nav:[Page,any][]=[["Dashboard",LayoutDashboard],["Stock Analysis",TrendingUp],["Company Intelligence",Building2],["Fundamentals",BarChart3],["Technical",Activity],["Decision",Zap],["Evidence Research",FlaskConical],["Portfolio",Wallet],["Risk",ShieldCheck],["Backtesting",PieChart],["News",Newspaper]];

function isObj(x:any){return x&&typeof x==="object"&&!Array.isArray(x)}
function arr(x:any):any[]{if(Array.isArray(x))return x;if(!x)return [];if(isObj(x)){for(const k of ["items","rows","results","records","values","data","positions","findings","issues","risks","competitors","quarters","sources"])if(Array.isArray(x[k]))return x[k];return [x]}return []}
function n(x:any,d=2){const v=Number(x);return Number.isFinite(v)?v.toFixed(d):"—"}
function money(x:any){const v=Number(x);if(!Number.isFinite(v))return"—";if(Math.abs(v)>=1e12)return`$${(v/1e12).toFixed(2)}T`;if(Math.abs(v)>=1e9)return`$${(v/1e9).toFixed(2)}B`;if(Math.abs(v)>=1e6)return`$${(v/1e6).toFixed(2)}M`;return`$${v.toLocaleString(undefined,{maximumFractionDigits:2})}`}
function pct(x:any){const v=Number(x);return Number.isFinite(v)?`${v.toFixed(2)}%`:"—"}
function text(x:any){if(x==null)return"—";if(typeof x==="string"||typeof x==="number"||typeof x==="boolean")return String(x);try{return JSON.stringify(x)}catch{return String(x)}}
function first(...xs:any[]){return xs.find(x=>x!==null&&x!==undefined&&x!=="")}
async function api(path:string){
 const token=localStorage.getItem("haviquant_access_token");
 const headers:HeadersInit=token?{Authorization:`Bearer ${token}`}:{};
 const r=await fetch(`${API}${path}`,{headers});
 if(!r.ok)throw new Error(`${r.status}: ${await r.text()}`);
 return r.json()
}

function Card({label,value,sub}:{label:string,value:any,sub?:string}){return <div className="metric"><span>{label}</span><strong>{value??"—"}</strong>{sub&&<small>{sub}</small>}</div>}
function Cards({items}:{items:[string,any,string?][]}){return <div className="cards">{items.map(([a,b,c],i)=><Card key={`${a}-${i}`} label={a} value={b} sub={c}/>)}</div>}
function Panel({title,children,action}:{title:string,children:React.ReactNode,action?:React.ReactNode}){return <section className="panel"><div className="panel-head"><h3>{title}</h3>{action}</div>{children}</section>}
function Loading({label="Loading intelligence…"}){return <div className="loading"><div className="spinner"/>{label}</div>}
function ErrorBox({error,retry}:{error:string,retry?:()=>void}){return <div className="errorbox"><b>Data error</b><span>{error}</span>{retry&&<button onClick={retry}>Retry</button>}</div>}
function Hero({ticker,name,badge,action}:{ticker:string,name?:string,badge:string,action?:React.ReactNode}){return <section className="hero"><div><span className="badge">{badge}</span><h2>{ticker} <small>{name||"—"}</small></h2><p>Market data, intelligence engines, portfolio context and research validation in one workspace.</p></div>{action}</section>}

function MarketChart({ticker,initialRows=[]}:{ticker:string,initialRows?:any[]}){
 const [period,setPeriod]=useState("1y"),[rows,setRows]=useState<any[]>(arr(initialRows)),[quote,setQuote]=useState<any>(null),[error,setError]=useState("");
 const loadHistory=useCallback(async()=>{try{setError("");const x=await api(`/history/${ticker}?period=${period}`);setRows(arr(x.rows))}catch(e:any){setError(e.message)}},[ticker,period]);
 useEffect(()=>{loadHistory()},[loadHistory]);
 useEffect(()=>{let mounted=true;const tick=async()=>{try{const q=await api(`/quote/${ticker}`);if(!mounted)return;setQuote(q);setRows(old=>{const p=Number(q.price);if(!Number.isFinite(p)||!old.length)return old;const last=old[old.length-1]||{};const now=new Date().toISOString();const item={...last,date:now,open:Number(last.open??p),high:Math.max(Number(last.high??p),p),low:Math.min(Number(last.low??p),p),close:p,volume:Number(q.volume??last.volume??0)};return [...old.slice(0,-1),item]})}catch{}};tick();const id=window.setInterval(tick,1000);return()=>{mounted=false;clearInterval(id)}},[ticker]);
 const pts=useMemo(()=>rows.filter(r=>Number.isFinite(Number(r.close))),[rows]);const W=1200,H=430,p=55;const vals=pts.map(r=>Number(r.close));const lo=vals.length?Math.min(...vals):0,hi=vals.length?Math.max(...vals):1,span=hi-lo||1;const x=(i:number)=>p+(i/Math.max(1,pts.length-1))*(W-p*2);const y=(v:number)=>H-p-(v-lo)/span*(H-p*2);const path=pts.map((r,i)=>`${i?"L":"M"} ${x(i).toFixed(1)} ${y(Number(r.close)).toFixed(1)}`).join(" ");
 return <Panel title={`Market Chart · ${ticker}`} action={<div className="periods">{periods.map(v=><button key={v} className={periodMap[v]===period?"selected":""} onClick={()=>setPeriod(periodMap[v])}>{v}</button>)}</div>}>{error?<ErrorBox error={error} retry={loadHistory}/>:<><div className="live-chart">{pts.length?<svg viewBox={`0 0 ${W} ${H}`} preserveAspectRatio="none"><defs><linearGradient id="hqfill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopOpacity=".35"/><stop offset="100%" stopOpacity="0"/></linearGradient></defs>{[0,1,2,3,4].map(i=><g key={i}><line className="grid" x1={p} x2={W-p} y1={p+i*(H-p*2)/4} y2={p+i*(H-p*2)/4}/><text className="axis" x="5" y={p+i*(H-p*2)/4+4}>{money(hi-(hi-lo)*i/4)}</text></g>)}{pts.length>1&&<><path d={`${path} L ${x(pts.length-1)} ${H-p} L ${x(0)} ${H-p} Z`} className="area"/><path d={path} className="line"/></>}<circle className="dot" cx={x(pts.length-1)} cy={y(Number(pts[pts.length-1].close))} r="5"/></svg>:<div className="empty">No historical price rows returned.</div>}</div><div className="chart-meta"><span>{pts.length} observations</span><span>Live quote refresh: 1s</span><span>Last: {quote?.price!=null?money(quote.price):"—"}</span></div></>}</Panel>
}

function useData(ticker:string){
 const [data,setData]=useState<Any>({}),[busy,setBusy]=useState(true),[error,setError]=useState("");
 const load=useCallback(async()=>{setBusy(true);setError("");try{const r=await Promise.allSettled([api(`/stock/${ticker}`),api(`/fundamental/${ticker}`)]);const base=r[0].status==="fulfilled"?r[0].value:{};if(!isObj(base)||!Object.keys(base).length)throw new Error("Stock workspace API returned no data.");setData({...base,fundamental:r[1].status==="fulfilled"?r[1].value:{},portfolio_context:null})}catch(e:any){setError(e.message||"API unavailable")}finally{setBusy(false)}},[ticker]);useEffect(()=>{load()},[load]);return{data,busy,error,reload:load}
}
function techValue(t:Any,key:string){return first(t?.[key],t?.[key.replace(/^sma_/,"sma")])}
function technicalCards(t:Any,q:Any){return [["Price",money(first(t?.price,q?.price))],["SMA 20",money(techValue(t,"sma_20"))],["SMA 50",money(techValue(t,"sma_50"))],["SMA 200",money(techValue(t,"sma_200"))],["RSI",n(t?.rsi)],["MACD",n(t?.macd)],["MACD Signal",n(t?.macd_signal)],["Volume Ratio",n(t?.volume_ratio)]] as [string,any][]}
function Dashboard({ticker,setPage}:{ticker:string,setPage:(p:Page)=>void}){const {data:d,busy,error,reload}=useData(ticker);if(busy&&!d.quote)return <Loading/>;if(error)return <ErrorBox error={error} retry={reload}/>;const q=d.quote||{},t=d.technical||{},dec=d.decision||{};return <><Hero ticker={ticker} name={d.company?.profile?.name} badge="360° LIVE INTELLIGENCE" action={<button className="primary" onClick={()=>setPage("Stock Analysis")}>Open Stock Analysis <ChevronRight size={16}/></button>}/><Cards items={[["Live Price",money(q.price)],["Change",pct(first(q.change_percent,q.change_pct))],["Technical Score",n(first(dec.technical_score,dec.score,t.technical_score),1)],["Decision",dec.action||dec.signal||"WATCH"]]}/><MarketChart ticker={ticker} initialRows={d.chart}/><Panel title="Technical Snapshot"><Cards items={technicalCards(t,q)}/></Panel><Panel title="Production Decision"><DecisionBox d={dec}/></Panel></>}
function DecisionBox({d}:{d:Any}){const decision=d||{};return <div className="decision"><div className="decision-main">{decision.action||decision.signal||"WATCH"}</div><div className="decision-row"><span>Technical Score</span><b>{n(first(decision.technical_score,decision.score),1)}</b></div><div className="decision-row"><span>Confidence</span><b>{n(decision.confidence,1)}</b></div><pre>{decision.rationale?text(decision.rationale):"Production decision engine output is preserved separately from research validation."}</pre></div>}

function StockAnalysis({ticker}:{ticker:string}){const {data:d,busy,error,reload}=useData(ticker);if(busy&&!d.quote)return <Loading/>;if(error)return <ErrorBox error={error} retry={reload}/>;const q=d.quote||{},t=d.technical||{},p=d.company?.profile||{},s=d.company?.scores||{},dec=d.decision||{},f=d.fundamental||{};return <><Hero ticker={ticker} name={p.name} badge="STOCK ANALYSIS · ENGINE CONNECTED" action={<button className="ghost" onClick={reload}><RefreshCw size={16}/> Refresh</button>}/><Cards items={[["Price",money(q.price)],["Technical Score",n(first(dec.technical_score,dec.score),1)],["Fundamental Score",n(first(f.scores?.fundamental_score,s.overall_company_score),1)],["Market Cap",money(p.market_cap)],["Decision",dec.action||dec.signal||"WATCH"]]}/><MarketChart ticker={ticker} initialRows={d.chart}/><Panel title="Technical Intelligence"><Cards items={technicalCards(t,q)}/></Panel><FundamentalPanel d={f}/><PortfolioContext data={d.portfolio_context}/><ResearchPreview ticker={ticker}/></>}
function PortfolioContext({data}:{data:any}){if(!data||(!data.shares&&!data.quantity))return <Panel title="Portfolio Context"><div className="empty">No portfolio position for this ticker.</div></Panel>;return <Panel title="Portfolio Context"><Cards items={[["Shares",first(data.shares,data.quantity)],["Average Cost",money(first(data.average_cost,data.avg_cost))],["Market Value",money(first(data.market_value,data.value))],["P/L",money(first(data.pnl,data.profit_loss))],["Risk",first(data.risk_level,data.risk)]]}/></Panel>}
function ResearchPreview({ticker}:{ticker:string}){const [d,setD]=useState<Any|null>(null),[busy,setBusy]=useState(false);const run=async()=>{setBusy(true);try{setD(await api(`/research/${ticker}?run=true`))}catch{}finally{setBusy(false)}};return <Panel title="Evidence Research · Validation"><div className="notice">Research is isolated from the production BUY/SELL decision.</div>{!d?<button className="primary" onClick={run} disabled={busy}>{busy?"Running Phase 3.8 → 3.9 → 3.9.1…":"Run Full Research"}</button>:<div className="horizon">{["phase_3_8","phase_3_9","phase_3_9_1"].map((k,i)=><div className="research-card" key={k}><b>PHASE {k.replace("phase_","").replace(/_/g,".")}</b><strong>{d[k]?.status||"—"}</strong><span>{i===1?`${Object.keys(d[k]?.horizons||{}).length} horizons validated`:i===0?"Walk-forward validation":"Dataset & score diagnostics"}</span></div>)}</div>}</Panel>}

function FundamentalPanel({d}:{d:Any}){const p=d?.profile||{},v=d?.valuation||{},pr=d?.profitability||{},g=d?.growth||{},e=d?.earnings||{},s=d?.scores||{};return <><Panel title="Fundamental Intelligence"><Cards items={[["Fundamental Score",n(first(s.fundamental_score,s.fundamental,s.overall,s.overall_company_score),1)],["Sector",p.sector],["Industry",p.industry],["Market Cap",money(p.market_cap)],["Employees",p.employees?.toLocaleString()],["P/E",n(first(v.trailing_pe,p.trailing_pe))],["Forward P/E",n(first(v.forward_pe,p.forward_pe))],["Profit Margin",pr.profit_margin!=null?pct(Number(pr.profit_margin)*100):"—"],["ROE",pr.roe!=null?pct(Number(pr.roe)*100):"—"],["Revenue Growth",g.revenue_growth!=null?pct(Number(g.revenue_growth)*100):"—"],["EPS",money(first(e.trailing_eps,e.forward_eps))],["Price",money(d.live_quote?.price||v.current_price)]]}/><p className="description">{p.description||p.summary||"No company description returned."}</p></Panel><Valuation d={v}/><Demand d={d.products_demand}/><DataSection title="Quarterly Fundamentals" data={d.quarters}/><DataSection title="Competition" data={d.competition}/><DataSection title="Fundamental Risks" data={d.risks}/></>}
function Valuation({d}:{d:Any}){return <Panel title="Valuation"><div className="value-grid">{Object.entries(d||{}).filter(([k])=>k!=="note").map(([k,v],i)=><div className="value-row" key={`${k}-${i}`}><span>{k.replace(/_/g," ")}</span><b>{typeof v==="number"?n(v,2):text(v)}</b></div>)}</div>{d?.note&&<div className="notice">{d.note}</div>}</Panel>}
function Demand({d}:{d:any}){const rows=arr(d?.future_demand);return <Panel title="Products / Demand"><div className="demand-head"><Card label="Current Demand" value={d?.current_demand_proxy||"—"}/><Card label="Future Demand" value="RESEARCH / VALIDATION"/></div>{rows.length?<div className="driver-grid">{rows.map((r,i)=><div className="driver" key={i}><b>{r.driver||"Demand driver"}</b><strong>{r.value||r.status||"—"}</strong><span>{r.timeline||""}</span><p>{r.evidence||r.impact||""}</p></div>)}</div>:<div className="empty">No structured demand drivers returned.</div>}<div className="notice">Future demand is an evidence/research layer; it is not a guaranteed forecast.</div></Panel>}
function DataSection({title,data}:{title:string,data:any}){const rows=arr(data);return <Panel title={title}>{!rows.length?<div className="empty"><b>No provider data returned.</b><br/>HaViQuant does not fabricate missing company-specific information.</div>:<div className="tablewrap"><table><tbody>{rows.slice(0,30).map((r,i)=><tr key={i}>{isObj(r)?Object.entries(r).slice(0,8).map(([k,v],j)=><td key={`${k}-${j}`}><span className="cell-label">{k.replace(/_/g," ")}</span><div>{text(v)}</div></td>):<td>{text(r)}</td>}</tr>)}</tbody></table></div>}</Panel>}

function Company({ticker}:{ticker:string}){const [d,setD]=useState<Any|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState("");const load=useCallback(()=>{setBusy(true);setError("");api(`/company/${ticker}`).then(x=>setD(x||{})).catch(e=>setError(e.message||"Unable to load company intelligence")).finally(()=>setBusy(false))},[ticker]);useEffect(load,[load]);if(busy)return <Loading/>;if(error)return <ErrorBox error={error} retry={load}/>;const data=d||{},p=data.profile||{},s=data.scores||{};return <><Hero ticker={ticker} name={p.name} badge="360° COMPANY INTELLIGENCE"/><Cards items={[["Sector",p.sector],["Industry",p.industry],["Market Cap",money(p.market_cap)],["Employees",p.employees?.toLocaleString()],["Overall Score",n(s.overall_company_score,1)],["Business Quality",n(s.business_quality,1)],["Growth Score",n(s.growth_score,1)],["Financial Strength",n(s.financial_strength,1)]]}/><Panel title="Business Overview"><p className="description">{p.description||p.summary||"No extended description returned."}</p></Panel><DataSection title="Products / Demand" data={data.products_demand?.future_demand}/><DataSection title="Backlog" data={data.backlog}/><DataSection title="Competition" data={data.competition}/><DataSection title="Risks" data={data.risks}/><DataSection title="Governance & Ethics" data={data.governance_ethics}/><DataSection title="Sources" data={data.sources}/></>}
function Fundamentals({ticker}:{ticker:string}){const [d,setD]=useState<Any|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState("");const load=useCallback(()=>{setBusy(true);setError("");api(`/fundamental/${ticker}`).then(x=>setD(x||{})).catch(e=>setError(e.message||"Unable to load fundamentals")).finally(()=>setBusy(false))},[ticker]);useEffect(load,[load]);if(busy)return <Loading/>;if(error)return <ErrorBox error={error} retry={load}/>;const data=d||{};return <><Hero ticker={ticker} name={data.profile?.name} badge="FUNDAMENTAL INTELLIGENCE"/><FundamentalPanel d={data}/></>}
function Technical({ticker}:{ticker:string}){const {data:d,busy,error,reload}=useData(ticker);if(busy&&!d.technical)return <Loading/>;if(error)return <ErrorBox error={error} retry={reload}/>;return <><Hero ticker={ticker} name={d.company?.profile?.name} badge="TECHNICAL INTELLIGENCE"/><Panel title="Technical Snapshot"><Cards items={technicalCards(d.technical||{},d.quote||{})}/></Panel><MarketChart ticker={ticker} initialRows={d.chart}/></>}
function Decision({ticker}:{ticker:string}){const [d,setD]=useState<Any|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState("");const load=useCallback(()=>{setBusy(true);setError("");api(`/decision/${ticker}`).then(x=>setD(x||{})).catch(e=>setError(e.message||"Unable to load decision")).finally(()=>setBusy(false))},[ticker]);useEffect(load,[load]);if(busy)return <Loading/>;if(error)return <ErrorBox error={error} retry={load}/>;const data=d||{},quote=data.quote||{},decision=data.decision||{};return <><Hero ticker={ticker} badge="PRODUCTION DECISION ENGINE"/><Cards items={[["Price",money(quote.price)],["Action",decision.action||decision.signal||"—"],["Technical Score",n(first(decision.technical_score,decision.score),1)],["Engine","CONNECTED"]]}/><Panel title="BUY / SELL / WATCH Decision"><DecisionBox d={decision}/></Panel></>}
function Research({ticker,backtesting=false}:{ticker:string,backtesting?:boolean}){const [d,setD]=useState<Any|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");const run=useCallback(()=>{setBusy(true);setError("");api(`/research/${ticker}?run=true`).then(x=>setD(x||{})).catch(e=>setError(e.message||"Unable to run research")).finally(()=>setBusy(false))},[ticker]);useEffect(()=>{api(`/research/${ticker}?run=true`).then(x=>setD(x||{})).catch(()=>{})},[ticker]);if(error)return <ErrorBox error={error} retry={run}/>;const data=d||{},hs=data.phase_3_9?.horizons||{};return <><Hero ticker={ticker} badge={backtesting?"BACKTESTING & VALIDATION":"EVIDENCE RESEARCH"} action={<button className="primary" onClick={run} disabled={busy}>{busy?"Running…":"Run Full Research"}</button>}/><div className="notice">Phase 3.8 → 3.9 → 3.9.1. Research is isolated from production decisions.</div>{!d||busy?<Loading label={busy?"Executing validation engine…":"Loading research…"}/>:<><Phase title="PHASE 3.8" status={data.phase_3_8?.status} body={<pre className="json">{JSON.stringify(data.phase_3_8?.summary||data.phase_3_8?.walk_forward,null,2)}</pre>}/><Phase title="PHASE 3.9" status={data.phase_3_9?.status} body={<div className="horizon">{Object.entries(hs).map(([k,v]:[string,any])=><div className="research-card" key={k}><b>{k}</b><strong>{n(v.current_score,1)}</strong><span>Percentile {n(v.current_percentile,1)}%</span><span>Observations {v.observations??"—"}</span><span>Pearson {n(v.pearson,3)}</span></div>)}</div>}/><Phase title="PHASE 3.9.1" status={data.phase_3_9_1?.status} body={<pre className="json">{JSON.stringify({dataset_audit:data.phase_3_9_1?.dataset_audit,score_diagnostics:data.phase_3_9_1?.score_diagnostics},null,2)}</pre>}/></>}</>}
function Phase({title,status,body}:{title:string,status:any,body:React.ReactNode}){return <Panel title={title} action={<span className={`status ${String(status).includes("COMPLETE")||status==="OK"?"ok":""}`}>{status||"READY"}</span>}>{body}</Panel>}
function Portfolio(){const [d,setD]=useState<Any|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState("");const load=useCallback(()=>{setBusy(true);setError("");api("/portfolio").then(x=>setD(x||{})).catch(e=>setError(e.message||"Unable to load portfolio")).finally(()=>setBusy(false))},[]);useEffect(load,[load]);if(busy)return <Loading/>;if(error)return <ErrorBox error={error} retry={load}/>;const data=d||{},doc=data.doctor||{},pos=arr(data.positions);return <><Hero ticker="PORTFOLIO" badge="PORTFOLIO INTELLIGENCE"/><Cards items={[["Cash",money(data.portfolio?.cash)],["Health",n(doc.health,1)],["Risk Score",n(doc.risk_score,1)],["Positions",pos.length],["P/L",money(first(doc.pnl,doc.total_pnl))]]}/><Panel title="Positions"><div className="tablewrap"><table><thead><tr><th>Ticker</th><th>Shares</th><th>Avg Cost</th><th>Value</th><th>P/L</th><th>Risk</th></tr></thead><tbody>{pos.map((r,i)=><tr key={i}><td><b>{r.ticker}</b></td><td>{n(r.shares,3)}</td><td>{money(r.average_cost)}</td><td>{money(first(r.market_value,r.value))}</td><td>{money(first(r.pnl,r.profit_loss))}</td><td>{text(first(r.risk,r.risk_level))}</td></tr>)}</tbody></table></div></Panel><DataSection title="Risk Findings" data={doc.findings||doc.risk_findings}/></>}
function Risk(){const [d,setD]=useState<Any|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState("");const load=useCallback(()=>{setBusy(true);setError("");api("/risk").then(x=>setD(x||{})).catch(e=>setError(e.message||"Unable to load risk")).finally(()=>setBusy(false))},[]);useEffect(()=>{load()},[load]);if(busy)return <Loading/>;if(error)return <ErrorBox error={error} retry={load}/>;const data=d||{},x=data.doctor||{};return <><Hero ticker="RISK" badge="PORTFOLIO RISK ENGINE"/><Cards items={[["Health",n(x.health,1)],["Risk Score",n(x.risk_score,1)],["Valuation Coverage",pct(x.valuation_coverage)],["P/L",money(first(x.pnl,x.total_pnl))]]}/><DataSection title="Risk Findings" data={x.findings||x.risk_findings}/><Panel title="Risk Engine Output"><pre className="json">{JSON.stringify(x,null,2)}</pre></Panel></>}
function News({ticker}:{ticker:string}){const [d,setD]=useState<any|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState("");const load=useCallback(()=>{setBusy(true);setError("");api(`/news/${ticker}`).then(x=>setD(x)).catch(e=>setError(e.message||"Unable to load news")).finally(()=>setBusy(false))},[ticker]);useEffect(()=>{load()},[load]);if(busy)return <Loading/>;if(error)return <ErrorBox error={error} retry={load}/>;return <><Hero ticker={ticker} badge="MARKET NEWS & EVENTS"/><Panel title={`${ticker} News`}><div className="news">{arr(d).map((r,i)=><article key={i}><b>{r.title||r.headline||"Market update"}</b><span>{r.publisher||r.source||""}</span><p>{r.summary||r.description||""}</p>{r.link&&<a href={r.link} target="_blank" rel="noreferrer">Open source</a>}</article>)}</div></Panel></>}
class UIErrorBoundary extends React.Component<{children:React.ReactNode},{error:string}>{state={error:""};static getDerivedStateFromError(e:any){return{error:e?.message||"Unexpected UI rendering error."}}render(){return this.state.error?<div className="content"><ErrorBox error={this.state.error}/></div>:this.props.children}}
function App(){const [page,setPage]=useState<Page>("Dashboard"),[ticker,setTicker]=useState("NVDA"),[query,setQuery]=useState("NVDA"),[open,setOpen]=useState(false);const go=(p:Page)=>{setPage(p);setOpen(false)};const content=page==="Dashboard"?<Dashboard ticker={ticker} setPage={go}/>:page==="Stock Analysis"?<StockAnalysis ticker={ticker}/>:page==="Company Intelligence"?<Company ticker={ticker}/>:page==="Fundamentals"?<Fundamentals ticker={ticker}/>:page==="Technical"?<Technical ticker={ticker}/>:page==="Decision"?<Decision ticker={ticker}/>:page==="Evidence Research"?<Research ticker={ticker}/>:page==="Portfolio"?<AuthGate><Portfolio/></AuthGate>:page==="Risk"?<Risk/>:page==="Backtesting"?<Research ticker={ticker} backtesting/>:<News ticker={ticker}/>;return <div className="app"><aside className={open?"open":""}><div className="brand"><div className="logo">HQ</div><div><b>HaViQuant</b><span>360° Investment Intelligence</span></div></div><div className="live"><i/> LIVE SYSTEM</div>{nav.map(([id,I])=><button key={id} className={page===id?"nav active":"nav"} onClick={()=>go(id)}><I size={18}/><span>{id}</span></button>)}<div className="sidefoot"><ShieldCheck size={15}/> Research isolated from production</div></aside><main><header><button className="mobile-menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><div><span className="eyebrow">MARKET INTELLIGENCE TERMINAL</span><h1>{page}</h1></div><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value.toUpperCase())} onKeyDown={e=>{if(e.key==="Enter"&&query.trim()){setTicker(query.trim().toUpperCase());go("Stock Analysis")}}} placeholder="Ticker (e.g. NVDA)"/><button onClick={()=>{if(query.trim()){setTicker(query.trim().toUpperCase());go("Stock Analysis")}}}><TrendingUp size={16}/></button></div></header><div className="content">{content}</div></main></div>}
createRoot(document.getElementById("root")!).render(<UIErrorBoundary><App/></UIErrorBoundary>);